### ISSUE TITLE
Live demonstration of the js sketch

### ISSUE THREAD

**Issue by mayank-kumar-giri** [joshihimanshu21/RandomMovingCars#1]
You can host the p5.js sketch using GitHub pages. Follow the following steps:
<ul>
<li>Just create a new branch named <b><i>"gh-pages"</i></b>.</li>
<li>Open settings, make <b><i>"gh-pages"</i></b> the default branch.</li>
<li>Delete the master branch.</li>
<li>Open the link given in settings after appending `"index.html" (your file's name)` at the end of it.</li>
</ul>

Enjoy!

**Comment by joshihimanshu21** [comment]
Just did it. Thanks a lot!
